### ISSUE TITLE
SkillHelper extractAmazonDate Parsing Issue

### ISSUE THREAD

**Issue by f2m2rd** [internetofvoice/vsms-core#1]
The extractAmazonDate method is unable to parse the following AMAZON.DATE:
`2018-WXX-6`

https://github.com/internetofvoice/vsms-core/blob/master/src/Helper/SkillHelper.php

**Comment by internetofvoice** [comment]
@f2m2rd, thanks for your bug report!

Indeed, this format is not parsed by `extractAmazonDate`. However, it's not mentioned in the [documentation](https://developer.amazon.com/de/docs/custom-skills/slot-type-reference.html#date) -- so I'm not sure, what this notation refers to. 

Do you have an example of which user input leads to this notation?

Thanks,
Alex.

**Comment by internetofvoice** [comment]
Please reopen with an example request, if problem occurs again.
